### PR TITLE
allow initialization of advertised info at the time of connection

### PR DESCRIPTION
**Pull request by asinghal**
at the moment, start() is called inside the constructor, so "added" event never gets advertised info. This change allows for nodes to send info upfront.

### CODE REVIEW

**Comment by asinghal** [comment]
hi Eli, were you able to merge this in ? Even if we put that into options, the object isnt put into node object by default, that will need a change. My perspective is that this isnt a configuration/ setting, so doesn't quite belong in the options object, but if you feel strongly about it, I am happy to modify and push that way. Do need the change and an updated package though :-)

many thanks

**Comment by skeggse** [comment]
I'm sorry, this project has mostly fallen off my radar :confused: 

I'd be happy to merge this, but I don't quite understand the use-case.

**Comment by asinghal** [comment]
thanks for your reply. here's what i am using it for: i need the slave processes / services to announce some information when they come up, that helps the master process determine their usage. the problem I have run into is that advertise only gets called after the process is already up, so even though the service advertises its details, the master has already stepped past "added" event. This is coming from the fact that the connection initialization happens inside the constructor itself. Hence the suggestion around setting this info at the time of initialization.

I guess you could put this inside the options object, I just think data in options defines the behavior of the process itself where as this information is more of a advertisement/ announcement for the master to consume. In any case, I am happy to push this into options if thats what makes sense

**Comment by skeggse** [comment]
Provided you're calling `advertise` just after constructing the `Discovery` instance, this will not be a problem. Node's event loop means that the process will not be "up" until several ticks after creating the `Discovery` instance.

Furthermore, no actual "connection" happens as node-discovery uses UDP broadcast, meaning that it's just sending out packets to anyone who will listen. If you can provide a reproducible test case that demonstrates the issue you described, I'll look into it, but the scenario you're describing isn't possible, as far as I can tell.

``` js
var Discovery = require('node-discovery');

var discovery = new Discovery();

// this happens before discovery has actually broadcasted anything
discovery.advertise({arbitrary: 'data'});
```

**Comment by asinghal** [comment]
fair enough:

## master.js

var Discovery = require('node-discovery').Discovery;

var discovery = new Discovery();

discovery.promote();

discovery.on("added", function(obj) {
  console.log("New node added to the network.");
  console.log(obj);
});

discovery.on("removed", function(obj) {
  console.log("Node removed from the network.");
  console.log(obj);
});

## slave.js

var Discovery = require('node-discovery').Discovery;

var discovery = new Discovery();

discovery.demote(true);

discovery.advertise({
  details: 'about',
  this: 'service'
});

discovery.on("added", function(obj) {
  console.log("New node added to the network.");
  console.log(obj);
});

discovery.on("removed", function(obj) {
  console.log("Node removed from the network.");
  console.log(obj);
});

start master.js with `node master.js`
start slave.js

the master doesn't see slave's announcement when the slave comes up

kill the slave process. master will see the advertised info now.

i am on a SSD + i7 quad core CPU, if that makes any difference.

**Comment by asinghal** [comment]
ignore me, if i move the demote line down, it works.

**Comment by skeggse** [comment]
If I run the above example, it all appears to work as expected (even if the demote line remains in the same place).

> i am on a SSD + i7 quad core CPU, if that makes any difference.

As am I.

Also for future reference, you can wrap your code with ``` (three backticks) to format them as code blocks.

**Pull request closed without merging**
